# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52a796e645cee0d8d04a613fc97f39967faaa734ccfcb8288adde977756f578e7bfd78059508e1657c744b907b944f6a1a68e9ce7ff5be980417ee7422282c14

test:
  secret_key_base: c58c2412564f9af232acb5939784cb537ddbf2e83fdce16c187faa9753ab1005d27c871cd390acf3e85370eab4f4f1d4617d909f1a22121ce8a019351210055c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
